name = "web-bruck"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

# Configuración para Cloudflare Pages
[env.production]
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"

# Variables de entorno para producción
[env.production.vars]
NODE_ENV = "production"
STATIC_EXPORT = "true"
